CONTAINER VPtimeyum
{
	NAME VPtimeyum;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		REAL TY_OPACITY { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		LONG TY_PROFILE
		{
			CYCLE
			{
				TY_PROFILE_FADE;
				TY_PROFILE_EXPONENTIAL;
				TY_PROFILE_CAMERA;
				TY_PROFILE_SPLINE;
			}
		}

		GROUP TY_GRP_STREAK
		{
			DEFAULT 1;
			REAL TY_LENGTH { UNIT PERCENT; MIN 0.0; MAX 400.0; MINSLIDER 0.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
			REAL TY_ANGLE { UNIT DEGREE; MIN -360.0; MAX 360.0; MINSLIDER -180.0; MAXSLIDER 180.0; CUSTOMGUI REALSLIDER; }
			BOOL TY_SYMMETRIC { }
			REAL TY_BACK_LENGTH { UNIT PERCENT; MIN 0.0; MAX 200.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_START_OFFSET { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 50.0; CUSTOMGUI REALSLIDER; }
			LONG TY_EDGE
			{
				CYCLE
				{
					TY_EDGE_WRAP;
					TY_EDGE_EXTEND;
					TY_EDGE_MIRROR;
					TY_EDGE_BLACK;
				}
			}
			REAL TY_FRAME_GAP { UNIT PERCENT; MIN 0.0; MAX 50.0; MINSLIDER 0.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_PROFILE
		{
			DEFAULT 1;
			REAL TY_FALLOFF { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_FALLOFF_CURVE { MIN 0.05; MAX 20.0; STEP 0.05; MINSLIDER 0.1; MAXSLIDER 5.0; CUSTOMGUI REALSLIDER; }
			REAL TY_DECAY { MIN 0.0; MAX 50.0; STEP 0.1; MINSLIDER 0.0; MAXSLIDER 15.0; CUSTOMGUI REALSLIDER; }
			SPLINE TY_CURVE
			{
				SHOWGRID_H;
				SHOWGRID_V;
				MINSIZE_H 200;
				MINSIZE_V 110;
				EDIT_H;
				EDIT_V;
				X_MIN 0;
				X_MAX 1;
				Y_MIN 0;
				Y_MAX 1;
				X_STEPS 1;
				Y_STEPS 1;
			}
		}

		GROUP TY_GRP_CAMERA
		{
			DEFAULT 1;
			REAL TY_TIMING_SHIFT { UNIT DEGREE; MIN -360.0; MAX 720.0; MINSLIDER 0.0; MAXSLIDER 360.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHUTTER_ANGLE { UNIT DEGREE; MIN 1.0; MAX 360.0; MINSLIDER 1.0; MAXSLIDER 360.0; CUSTOMGUI REALSLIDER; }
			REAL TY_PULLDOWN_ANGLE { UNIT DEGREE; MIN 1.0; MAX 359.0; MINSLIDER 30.0; MAXSLIDER 330.0; CUSTOMGUI REALSLIDER; }
			REAL TY_CLAW_EASE { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_EXPOSURE
		{
			DEFAULT 1;
			REAL TY_SMEAR { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_GAIN { MIN 0.0; MAX 100.0; STEP 0.01; MINSLIDER 0.0; MAXSLIDER 5.0; CUSTOMGUI REALSLIDER; }
			LONG TY_BLEND
			{
				CYCLE
				{
					TY_BLEND_EXPOSURE;
					TY_BLEND_ADD;
					TY_BLEND_SCREEN;
					TY_BLEND_LIGHTEN;
				}
			}
			REAL TY_THRESHOLD { MIN 0.0; MAX 1000.0; STEP 0.01; MINSLIDER 0.0; MAXSLIDER 2.0; CUSTOMGUI REALSLIDER; }
			REAL TY_KNEE { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_CLEANUP { MIN 0.0; MAX 100.0; STEP 0.1; MINSLIDER 0.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_GHOST
		{
			DEFAULT 0;
			BOOL TY_GHOST { }
			LONG TY_GHOST_COUNT { MIN 1; MAX 16; }
			REAL TY_GHOST_OFFSET { UNIT PERCENT; MIN -200.0; MAX 200.0; MINSLIDER -50.0; MAXSLIDER 50.0; CUSTOMGUI REALSLIDER; }
			REAL TY_GHOST_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_GHOST_DECAY { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_GHOST_LENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 20.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_FRAME
		{
			DEFAULT 0;
			REAL TY_ROLL { UNIT PERCENT; MIN -1000.0; MAX 1000.0; MINSLIDER -100.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_ROLL_BAR { UNIT PERCENT; MIN 0.0; MAX 50.0; MINSLIDER 0.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
			REAL TY_ROLL_BAR_SOFT { UNIT PERCENT; MIN 0.0; MAX 500.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_COLOR
		{
			DEFAULT 0;
			COLOR TY_TINT { }
			REAL TY_SATURATION { UNIT PERCENT; MIN 0.0; MAX 400.0; MINSLIDER 0.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
			REAL TY_CHROMA { UNIT PERCENT; MIN -90.0; MAX 90.0; MINSLIDER -30.0; MAXSLIDER 30.0; CUSTOMGUI REALSLIDER; }
			REAL TY_BREAKUP { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_BREAKUP_SCALE { MIN 0.5; MAX 1000.0; STEP 0.5; MINSLIDER 1.0; MAXSLIDER 50.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_SHAKE
		{
			DEFAULT 0;
			BOOL TY_SHAKE { }
			REAL TY_SHAKE_AMOUNT { UNIT PERCENT; MIN 0.0; MAX 1000.0; MINSLIDER 0.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_FREQ { MIN 0.0; MAX 240.0; STEP 0.1; MINSLIDER 0.0; MAXSLIDER 30.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_SMOOTH { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			LONG TY_SHAKE_SEED { MIN 0; MAX 999999; }
			SEPARATOR { LINE; }
			REAL TY_SHAKE_LENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_SMEAR { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_ANGLE { UNIT DEGREE; MIN 0.0; MAX 180.0; MINSLIDER 0.0; MAXSLIDER 30.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_TIMING { UNIT DEGREE; MIN 0.0; MAX 360.0; MINSLIDER 0.0; MAXSLIDER 90.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_GHOST { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_ROLL { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 50.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_WEAVE_X { MIN 0.0; MAX 200.0; STEP 0.1; MINSLIDER 0.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
			REAL TY_SHAKE_WEAVE_Y { MIN 0.0; MAX 200.0; STEP 0.1; MINSLIDER 0.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP TY_GRP_OUTPUT
		{
			DEFAULT 0;
			LONG TY_COLORSPACE
			{
				CYCLE
				{
					TY_CS_LINEAR;
					TY_CS_SRGB;
					TY_CS_GAMMA24;
					TY_CS_LOGC3;
					TY_CS_SLOG3;
				}
			}
			BOOL TY_AFFECT_ALPHA { }
			LONG TY_STAGE
			{
				CYCLE
				{
					TY_STAGE_RENDER;
					TY_STAGE_FRAME;
				}
			}
		}
	}
}
