#pragma once

// Parameter slots in the order they appear in the effect panel. Slot 0 is the input layer.
// Topic start/end entries occupy a slot too.
enum TimeyumParamIndex {
    P_INPUT = 0,

    P_OPACITY,
    P_PROFILE,

    P_STREAK_TOPIC,
    P_LENGTH,
    P_ANGLE,
    P_SYMMETRIC,
    P_BACK_LENGTH,
    P_START_OFFSET,
    P_EDGE,
    P_FRAME_GAP,
    P_STREAK_END,

    P_PROFILE_TOPIC,
    P_FALLOFF,
    P_FALLOFF_CURVE,
    P_DECAY,
    P_PROFILE_END,

    P_CAMERA_TOPIC,
    P_TIMING_SHIFT,
    P_SHUTTER_ANGLE,
    P_PULLDOWN_ANGLE,
    P_CLAW_EASE,
    P_CAMERA_END,

    P_EXPOSURE_TOPIC,
    P_SMEAR,
    P_GAIN,
    P_BLEND,
    P_THRESHOLD,
    P_KNEE,
    P_CLEANUP,
    P_EXPOSURE_END,

    P_GHOST_TOPIC,
    P_GHOST,
    P_GHOST_COUNT,
    P_GHOST_OFFSET,
    P_GHOST_STRENGTH,
    P_GHOST_DECAY,
    P_GHOST_LENGTH,
    P_GHOST_END,

    P_FRAME_TOPIC,
    P_ROLL,
    P_ROLL_BAR,
    P_ROLL_BAR_SOFT,
    P_FRAME_END,

    P_COLOR_TOPIC,
    P_TINT,
    P_SATURATION,
    P_CHROMA,
    P_BREAKUP,
    P_BREAKUP_SCALE,
    P_COLOR_END,

    P_SHAKE_TOPIC,
    P_SHAKE,
    P_SHAKE_AMOUNT,
    P_SHAKE_FREQ,
    P_SHAKE_SMOOTH,
    P_SHAKE_SEED,
    P_SHAKE_LENGTH,
    P_SHAKE_SMEAR,
    P_SHAKE_ANGLE,
    P_SHAKE_TIMING,
    P_SHAKE_GHOST,
    P_SHAKE_ROLL,
    P_SHAKE_WEAVE_X,
    P_SHAKE_WEAVE_Y,
    P_SHAKE_END,

    P_OUTPUT_TOPIC,
    P_COLORSPACE,
    P_AFFECT_ALPHA,
    P_OUTPUT_END,

    P_COUNT
};

// IDs stored in project files. Never renumber or reuse: new parameters get the next free ID
// and are added at the end of the panel order.
enum TimeyumParamId {
    ID_OPACITY = 1, ID_PROFILE,
    ID_STREAK_TOPIC, ID_LENGTH, ID_ANGLE, ID_SYMMETRIC, ID_BACK_LENGTH, ID_START_OFFSET, ID_EDGE, ID_FRAME_GAP, ID_STREAK_END,
    ID_PROFILE_TOPIC, ID_FALLOFF, ID_FALLOFF_CURVE, ID_DECAY, ID_PROFILE_END,
    ID_CAMERA_TOPIC, ID_TIMING_SHIFT, ID_SHUTTER_ANGLE, ID_PULLDOWN_ANGLE, ID_CLAW_EASE, ID_CAMERA_END,
    ID_EXPOSURE_TOPIC, ID_SMEAR, ID_GAIN, ID_BLEND, ID_THRESHOLD, ID_KNEE, ID_CLEANUP, ID_EXPOSURE_END,
    ID_GHOST_TOPIC, ID_GHOST, ID_GHOST_COUNT, ID_GHOST_OFFSET, ID_GHOST_STRENGTH, ID_GHOST_DECAY, ID_GHOST_LENGTH, ID_GHOST_END,
    ID_FRAME_TOPIC, ID_ROLL, ID_ROLL_BAR, ID_ROLL_BAR_SOFT, ID_FRAME_END,
    ID_COLOR_TOPIC, ID_TINT, ID_SATURATION, ID_CHROMA, ID_BREAKUP, ID_BREAKUP_SCALE, ID_COLOR_END,
    ID_SHAKE_TOPIC, ID_SHAKE, ID_SHAKE_AMOUNT, ID_SHAKE_FREQ, ID_SHAKE_SMOOTH, ID_SHAKE_SEED, ID_SHAKE_LENGTH,
    ID_SHAKE_SMEAR, ID_SHAKE_ANGLE, ID_SHAKE_TIMING, ID_SHAKE_GHOST, ID_SHAKE_ROLL, ID_SHAKE_WEAVE_X, ID_SHAKE_WEAVE_Y, ID_SHAKE_END,
    ID_OUTPUT_TOPIC, ID_COLORSPACE, ID_AFFECT_ALPHA, ID_OUTPUT_END
};
